const mongoose = require("mongoose")

const BookSchema=mongoose.Schema({
    tid:{
        type:String, 
    },
    userDetailes:{
        name:{
            type:String,
            required:true
        },
        email:{
            type:String,
            required:true
        },
        phone:{
            type:Number,
            required:true
        },
    },
    date:{
        type:String
    },
    serviceId:{
        type:mongoose.SchemaTypes.ObjectId,
        ref:"service"
    },
    slotDetailes:{
        startTime:{
            type:String,
            default:""
        },
        endTime:{
            type:String,
            default:""
        },
        day:{
            type:String,
            default:""
        }
    },
    order_id:{
        type:String,
        required:true
    },
    status:{
        type:String,
        default:"pending"
    },
    receipt:{
        type:String,
        default:""
    },
    amount:{
        type:Number,
        default:0
    },
    serviceName:{
        type:String,
        default:""
    },
    mailSend:{
        type:Boolean,
        default:false
    },
    docid:{
        type:mongoose.Types.ObjectId
    }
})

const BookSlot=mongoose.model('bookslot',BookSchema)
module.exports=BookSlot